[tool.poetry]
name = "mastering-taproot"
version = "0.1.0"
description = ""
authors = ["Artemiy <artem.pospelov2018@yandex.ru>"]
package-mode = false

# ðŸ”¥ ÐšÐ»ÑŽÑ‡ÐµÐ²Ð¾Ðµ: ÑƒÐºÐ°Ð·Ñ‹Ð²Ð°ÐµÐ¼ Python Ð·Ð´ÐµÑÑŒ, Ð° Ð½Ðµ Ð² [project]
[tool.poetry.dependencies]
python = ">=3.12"
bitcoinlib = ">=0.7.7,<0.8.0"
fastecdsa = ">=3.0.1,<4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
